import smtplib
import os
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart


def send_email_to_customer(
    to_email: str,
    customer_name: str,
    subject: str,
    body: str
) -> dict:
    """
    Send an actual email to the customer via SMTP.
    Returns {"success": bool, "message": str}
    """
    smtp_host = os.getenv("SMTP_HOST", "smtp.gmail.com")
    smtp_port = int(os.getenv("SMTP_PORT", "587"))
    smtp_user = os.getenv("SMTP_USER", "")
    smtp_pass = os.getenv("SMTP_PASS", "")
    from_name = os.getenv("FROM_NAME", "FinCollect Solutions")

    if not smtp_user or not smtp_pass:
        return {
            "success": False,
            "message": "SMTP credentials not configured. Please set SMTP_USER and SMTP_PASS in your .env file."
        }

    try:
        msg = MIMEMultipart("alternative")
        msg["Subject"] = subject
        msg["From"] = f"{from_name} <{smtp_user}>"
        msg["To"] = f"{customer_name} <{to_email}>"

        # Plain text version
        text_part = MIMEText(body, "plain", "utf-8")

        # HTML version — wrap the plain body nicely
        html_body = body.replace("\n", "<br>")
        html_content = f"""
        <html>
        <body style="font-family:Arial,sans-serif;max-width:600px;margin:auto;padding:24px;color:#1e293b;">
          <div style="border-left:4px solid #3b82f6;padding-left:16px;margin-bottom:24px;">
            <h2 style="margin:0;color:#1e40af;">FinCollect Solutions</h2>
            <p style="margin:4px 0 0;color:#64748b;font-size:13px;">AI Payment Reminder System</p>
          </div>
          <div style="line-height:1.7;font-size:15px;">
            {html_body}
          </div>
          <hr style="margin:32px 0;border:none;border-top:1px solid #e2e8f0;">
          <p style="font-size:11px;color:#94a3b8;text-align:center;">
            This email was generated by AI Payment Reminder Assistant · FinCollect Solutions<br>
            If you have questions, reply to this email.
          </p>
        </body>
        </html>
        """
        html_part = MIMEText(html_content, "html", "utf-8")

        msg.attach(text_part)
        msg.attach(html_part)

        with smtplib.SMTP(smtp_host, smtp_port, timeout=15) as server:
            server.ehlo()
            server.starttls()
            server.ehlo()
            server.login(smtp_user, smtp_pass)
            server.sendmail(smtp_user, [to_email], msg.as_string())

        return {"success": True, "message": f"Email sent successfully to {to_email}"}

    except smtplib.SMTPAuthenticationError:
        return {"success": False, "message": "SMTP authentication failed. Check your SMTP_USER and SMTP_PASS."}
    except smtplib.SMTPException as e:
        return {"success": False, "message": f"SMTP error: {str(e)}"}
    except Exception as e:
        return {"success": False, "message": f"Failed to send email: {str(e)}"}
